spring:
  application:
    name: notification-service
  profiles:
    active: default
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/goodsdb
    platform: postgres
    username: moon
    password: 1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/

fcm:
  certification: firebase/certification.json
