server:
  port: 9003

spring:
  application:
    name: notification-service
  profiles:
    active: default
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/

fcm:
  certification: firebase/certification.json